version: "3"

services:
    dtserver:
      build:
        context: ./Dynatrace-Server
        args:
          - TIMEZONE=${TIMEZONE}
          - DT_HOME=${DT_HOME}
          - VERSION=${VERSION}
          - BUILD_VERSION=${BUILD_VERSION}
          - DT_SERVER_LICENSE_KEY_FILE_URL=${DT_SERVER_LICENSE_KEY_FILE_URL}
      container_name: "${DT_SERVER_NAME}"
      image: "dynatrace/server:7.1"
      environment:
        - TZ=${TIMEZONE}
        - COMPOSE_PROJECT_NAME
        - DT_HOME
        - DT_SERVER_LICENSE_KEY_FILE_URL
        - APPMON_COLLECTOR_SERVER_SSL_PORT
      ports:
        # Browser to server ports NonSSL 8020 SSL 8021 (to start the Webstart Client)
        - "${APPMON_WEB_CLIENT_NONSSL_PORT:-8020}:8020"
        - "${APPMON_WEB_CLIENT_SSL_PORT:-8021}:8021"
        # 8040  Non SSL Collector to server port for Web Base Agents (or direct agent to server)
        # 8041  SSL Collector to server port for Web Base Agents (or direct agent to server)
        - "${APPMON_ONEAGENT_NONSSL_SERVER_PORT:-8040}:8040"
        - "${APPMON_ONEAGENT_SSL_SERVER_PORT:-8041}:8041"
        # 2021 Client to Frontend Server - non SSL
        - "${APPMON_CLIENT_NONSSL_PORT:-2021}:2021"
        # 8023 Client to Frontend Server - encrypted via HTTP tunnel
        - "${APPMON_CLIENT_SSL_PORT:-8023}:8023"
        # 6699 Collector to Server SSL
        - "${APPMON_COLLECTOR_SERVER_SSL_PORT:-6699}:6699"
        # 9998 - Legacy Agent to server embedded Collector (default)
        - 9911:9911
        # Web dashboards
      volumes:
        - /tmp/log/dynatrace/server:${DT_HOME}/log/server
      networks:
        - appmon


    easytravel:
      build:
        context: ./easytravel
        args:
          - TIMEZONE=${TIMEZONE}
          - VERSION=${VERSION}
          - BUILD_VERSION=${BUILD_VERSION}
          - EASYTRAVEL_VERSION
          - EASYTRAVEL_BUILD
          - DT_SERVER_NAME
          - APPMON_COLLECTOR_PORT
      container_name: "easytravel"
      image: "dynatrace/easytravel:7.1"
      environment:
          - TZ=${TIMEZONE}
      ports:
          - "8079:8079"
          - "8094:8094"
      volumes:
        - /tmp/log/dynatrace/agent:/opt/dynatrace-${VERSION}/log
        - /tmp/log/dynatrace/easytravel:/root/.dynaTrace/easyTravel ${EASYTRAVEL_VERSION}/easyTravel/log
      networks:
        - appmon
networks:
    appmon:
        driver: bridge
